name: Test
on: [push]
jobs:
  unit-test-go:
    name: Unit Test golang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run unit test
        run: |
          make test
